# Generated by Django 4.1.5 on 2023-01-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uslugi', models.CharField(blank=True, default='', max_length=150, verbose_name='Услуги')),
                ('content', models.TextField(blank=True, default='', verbose_name='Содержание')),
                ('phone_number', models.CharField(default='', max_length=13, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Клиника',
                'verbose_name_plural': 'Клиники',
                'ordering': ['-pk'],
            },
        ),
    ]
